name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Deploy to server
      run: |
        ssh -o "StrictHostKeyChecking=no" root@${{ secrets.SERVER_IP }} "cd /usr/src/stock_analyse_tool_back_end_flask && git pull origin master && sudo systemctl restart flaskapp.service"
